id: P000209
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: ༄༅། །མཁན་ཆེན་ཨ་པད་རིན་པོ་ཆེའི་ཞལ་གསུང་བློ་སྦྱོང་དོན་བདུན་མའི་བཀའ་ཁྲིད་བཞུགས་སོ།
    །
  authors:
  - མཛད་པ་པོ། མཁན་ཆེན་ཨ་པད་རིན་པོ་ཆེ།
  layers:
  - book_title
  - author
  - quotation
  id: IBA-MT-01-1
web_metadata:
  title:
    en: A Commentary on the Seven Points of Mind Training
    bo: བློ་སྦྱོང་དོན་བདུན་མའི་འགྲེལ་པ་བཞུགས་སོ།།
  collection:
    en: IBA Mind Training Series–  Book 1
    bo: རྒྱལ་ཡོངས་གསུང་རབ་བློ་སྦྱོང་བསྟར་རིམ།–  དེབ། ༡
  author:
    en: Khenchen Appey Rinpoche
    bo: མཁན་ཆེན་ཨ་པད་རིན་པོ་ཆེ།
  pusblisher:
    en: IBA Publications
    bo: རྒྱལ་ཡོངས་གསུང་རབ་སློབ་གཉེར་ཁང་།
  sku: IBA-MT-01-1
  category:
    en: Mind Training
    bo: བློ་སྦྱོང།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: IBA-MT-01-1.epub
  description:
    en: ''
    bo: ''
